---
- hosts: webservers
  become: true
  become_user: root
  become_method: sudo
  tasks: 
    - name: give ec2 a change to fully bake
      delay: 10
      file:
        path: /root/web_script.debug
        state: touch

    - name: update system
      register: task_result
      until: task_result.rc == 0
      retries: 6
      delay: 10
      ignore_errors: yes
      yum:
        name: '*'
        state: latest

    - name: install httpd 
      yum: 
        name: httpd
        state: latest

    - name: kick off httpd
      service:
        name: httpd
        enabled: yes
        state: started

    - name: copy html file over
      copy:
        src: ../../../app/index.html
        dest: /var/www/html/index.html
        owner: apache
        group: apache
        mode: 0644

    - name: customize the html file
      shell: sed -i -e s/HOSTNAME/`hostname`/ /var/www/html/index.html
      become: true
      become_user: root

    - name: html file customized using Jinja
      template: 
        src: ../../../app/templateExample.j2
        dest: /var/www/html/servers.html
        owner: apache
        group: apache
        mode: 0644

    - name: copy another html file 
      copy: src=../../../app/other.html dest=/var/www/html/other.html mode=0644 owner=apache group=apache

    - name: customize above html file using lineinfile
      lineinfile: dest=/var/www/html/other.html regexp=HOSTNAME line="File was modified by lineinfile with no real reason"
