---
- hosts: webservers
  become: true
  become_user: root
  become_method: sudo
  tasks: 
    - name: give ec2 a change to fully bake
      delay: 10
      file:
        path: /root/web_script.debug
        state: touch

    - name: update system
      register: task_result
      until: task_result.rc == 0
      retries: 6
      delay: 10
      ignore_errors: yes
      yum:
        name: '*'
        state: latest

    - name: install httpd 
      yum: 
        name: httpd
        state: latest

    - name: kick off httpd
      service:
        name: httpd
        enabled: yes
        state: started

    - name: copy html file over
      copy:
        src: ../../../app/index.html
        dest: /var/www/html/index.html
        owner: apache
        group: apache
        mode: 0644

    - name: customize the html file
      command: hn=`hostname`;sed -i -e s/HOSTNAME/$hn/ /var/www/html/index.html
